import type { Metadata } from "next";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="sticky top-0 z-50 border-b-2 border-black bg-white/30 backdrop-blur">
          <nav className="max-w-6xl mx-auto flex items-center gap-3 p-4 bg-white/30">
            <Link
              href="/"
              className="border-2 border-black px-4 py-2 font-black text-sm uppercase hover:bg-black hover:text-white transition-colors"
            >
              Home
            </Link>
            <Link
              href="/chat"
              className="border-2 border-black px-4 py-2 font-black text-sm uppercase hover:bg-black hover:text-white transition-colors"
            >
              AI Chat
            </Link>
            <Link
              href="/send-email"
              className="border-2 border-black px-4 py-2 font-black text-sm uppercase hover:bg-black hover:text-white transition-colors"
            >
              Send Email
            </Link>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
